# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YallaNezam' do


pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'DropDown'
pod 'SwiftyJSON'
pod 'Alamofire'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YallaNezam

  target 'YallaNezamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YallaNezamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
