# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Transporter' do

pod 'SACodedTextField'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire', '~> 4.4'
pod 'AlamofireObjectMapper', '~> 4.0'
 pod 'ReachabilitySwift', '~> 3'
pod 'Kingfisher', '~> 4.0'
pod "CZPicker"
pod 'SwiftyJSON', '>= 2.1.3'
pod 'Firebase'
pod 'Firebase/Messaging'
pod 'WWCalendarTimeSelector'
pod 'KOPinCodeView', '~> 0.1.1'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Transporter

end
